### PR TITLE
fix: tdengine swarm cluster(3 mnodes) startup error

### LINKED ISSUE #19837: tdengine-3.0.2.4 swarm cluster (3mnode-3dnodes-3replica):  2/3 nodes restart cannot be recovered
**Bug Description**

三个低性能 PC 的 docker swarm 集群灾备测试 ( 3mnode-3dnodes-3replica )
-   单独关闭 `server-01/server-02`, 插入数据，`TDengine` 集群运行正常, 可看到同步日志
-   同时关闭 `server-01` 和 `server-02`, 重新开机后，`td-2` 和 `td-3` 显示以下报错，`TDengine` 集群无法正常部署
```
kun_td-2.1.ktrldl0v6p8k@server-01    | 2: service ok
kun_td-2.1.ktrldl0v6p8k@server-01    | execute create dnode
kun_td-2.1.ktrldl0v6p8k@server-01    | Welcome to the TDengine Command Line Interface, Client Version:3.0.2.4
kun_td-2.1.ktrldl0v6p8k@server-01    | Copyright (c) 2022 by TDengine, all rights reserved.
kun_td-2.1.ktrldl0v6p8k@server-01    | 
kun_td-2.1.ktrldl0v6p8k@server-01    | failed to connect to server, reason: Sync not leader
kun_td-2.1.ktrldl0v6p8k@server-01    | 
```

**To Reproduce**
- 构建swarm集群，重启两个节点（或重启集群）

**Expected Behavior**
重启后，正常部署 tdengine 集群

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 22.04 LTS
 - 8G Memory, CPU i5-1135G7, 512G SSD
 - TDengine Version 3.0.2.4

**Additional Context**

### PR DESCRIPTION
**Pull request by lazyky**
add check if dnode has been created when TDengine docker image starts

Resolves #19837

### CODE REVIEW

File: packaging/docker/bin/entrypoint.sh [hunk 1]
```diff
@@ -53,15 +53,18 @@ else
...
-        echo ${es}
-        if [ "${es%%:*}" -eq 2 ]; then
-            echo "execute create dnode"
-            taos -h $FIRST_EP_HOST -P $FIRST_EP_PORT -s "create dnode \"$FQDN:$SERVER_PORT\";"
-            break
-        fi
-        sleep 1s
-    done
+    # check if dnode has been created
+    if [ ! -f "$DATA_DIR/dnode/dnode.json" ]; then
```
Comment (zitsen) [inline packaging/docker/bin/entrypoint.sh]: Actually, the check should be fixed in [Line 46](https://github.com/taosdata/TDengine/blob/6f53e8ed764a82ecfa92787838bfed0b9128b38b/packaging/docker/bin/entrypoint.sh#L46), since TDengine 3.0 has changed its data structure - its a mistake though.

**Review by zitsen — CHANGES_REQUESTED** [review]

File: packaging/docker/bin/entrypoint.sh (hunk 1 above)
Comment (lazyky) [reply packaging/docker/bin/entrypoint.sh]: I agree with your suggestion and have changed it.

**Review by sangshuduo — APPROVED** [review]
LGTM
